#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Plaga44.Rules;

namespace Plaga44.Editor
{
    /// <summary>
    /// Exports CombatRule ScriptableObjects to JSON for re-import into Neo4j.
    /// Menu: CYBERNOMAD/Rules/Export to JSON
    ///
    /// Scans Assets/Data/Rules/ for all CombatRule assets and writes a JSON array
    /// compatible with RuleImporter (round-trip safe).
    ///
    /// Also produces Cypher CREATE statements for direct Neo4j import.
    /// </summary>
    public static class RuleExporter
    {
        private const string RULES_DIR = "Assets/Data/Rules";
        private const string LOG = "[Plaga44/RuleExporter]";

        [MenuItem("CYBERNOMAD/Rules/Export to JSON", false, 201)]
        public static void ExportToJson()
        {
            CombatRule[] rules = LoadAllRules();
            if (rules.Length == 0)
            {
                EditorUtility.DisplayDialog("No Rules Found",
                    $"No CombatRule assets found in {RULES_DIR}.\nCreate rules first via the inspector.", "OK");
                return;
            }

            string defaultName = $"combat_rules_{DateTime.Now:yyyyMMdd_HHmmss}.json";
            string path = EditorUtility.SaveFilePanel("Export Combat Rules", "", defaultName, "json");
            if (string.IsNullOrEmpty(path)) return;

            string json = BuildJson(rules);
            File.WriteAllText(path, json, Encoding.UTF8);

            Debug.Log($"{LOG} Exported {rules.Length} rules to: {path}");
            EditorUtility.DisplayDialog("Export Complete",
                $"Exported {rules.Length} rule(s) to:\n{path}", "OK");
        }

        [MenuItem("CYBERNOMAD/Rules/Export to Cypher (Neo4j)", false, 202)]
        public static void ExportToCypher()
        {
            CombatRule[] rules = LoadAllRules();
            if (rules.Length == 0)
            {
                EditorUtility.DisplayDialog("No Rules Found",
                    $"No CombatRule assets found in {RULES_DIR}.", "OK");
                return;
            }

            string defaultName = $"combat_rules_{DateTime.Now:yyyyMMdd_HHmmss}.cypher";
            string path = EditorUtility.SaveFilePanel("Export as Cypher", "", defaultName, "cypher");
            if (string.IsNullOrEmpty(path)) return;

            string cypher = BuildCypher(rules);
            File.WriteAllText(path, cypher, Encoding.UTF8);

            Debug.Log($"{LOG} Exported {rules.Length} rules as Cypher to: {path}");
            EditorUtility.DisplayDialog("Cypher Export Complete",
                $"Exported {rules.Length} rule(s) to:\n{path}", "OK");
        }

        /// <summary>
        /// Returns the JSON export as a string (callable from other editor scripts / CI).
        /// </summary>
        public static string BuildJson(CombatRule[] rules)
        {
            var sb = new StringBuilder();
            sb.AppendLine("[");

            for (int i = 0; i < rules.Length; i++)
            {
                CombatRule r = rules[i];
                sb.Append("  {");
                sb.Append($"\n    \"name\": \"{EscapeJson(r.name)}\",");
                sb.Append($"\n    \"source\": \"{r.sourceObjectType}\",");
                sb.Append($"\n    \"hitZone\": \"{r.hitZone}\",");
                sb.Append($"\n    \"threshold\": {r.forceThreshold},");
                sb.Append($"\n    \"effect\": \"{r.resultEffect}\",");
                sb.Append($"\n    \"stunDuration\": {r.stunDuration},");
                sb.Append($"\n    \"knockBackForce\": {r.knockBackForce},");
                sb.Append($"\n    \"woundDamage\": {r.woundDamage},");
                sb.Append($"\n    \"description\": \"{EscapeJson(r.description)}\"");
                sb.Append("\n  }");

                if (i < rules.Length - 1) sb.Append(",");
                sb.AppendLine();
            }

            sb.Append("]");
            return sb.ToString();
        }

        /// <summary>
        /// Generates Cypher CREATE statements for Neo4j.
        /// Creates ObjectType, HitZone, StatusEffect nodes and HITS + CAUSES relationships.
        /// </summary>
        public static string BuildCypher(CombatRule[] rules)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by Plaga44 RuleExporter");
            sb.AppendLine($"// Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            // Collect unique types and zones for CREATE statements.
            var objectTypes = new HashSet<string>();
            var hitZones = new HashSet<string>();
            var effects = new HashSet<string>();

            foreach (CombatRule r in rules)
            {
                objectTypes.Add(r.sourceObjectType.ToString());
                hitZones.Add(r.hitZone.ToString());
                effects.Add(r.resultEffect.ToString());
            }

            sb.AppendLine("// --- Nodes ---");
            foreach (string ot in objectTypes)
                sb.AppendLine($"MERGE (ot_{ot}:ObjectType {{name: '{ot}'}})");

            sb.AppendLine();
            foreach (string hz in hitZones)
                sb.AppendLine($"MERGE (hz_{hz}:HitZone {{name: '{hz}'}})");

            sb.AppendLine();
            foreach (string ef in effects)
                sb.AppendLine($"MERGE (se_{ef}:StatusEffect {{name: '{ef}'}})");

            sb.AppendLine();
            sb.AppendLine("// --- Rules (relationships) ---");

            foreach (CombatRule r in rules)
            {
                string ot = r.sourceObjectType.ToString();
                string hz = r.hitZone.ToString();
                string ef = r.resultEffect.ToString();
                string ruleName = EscapeCypher(r.name);
                string desc = EscapeCypher(r.description);

                sb.AppendLine(
                    $"MERGE (ot_{ot})-[:HITS {{rule: '{ruleName}', threshold: {r.forceThreshold}, description: '{desc}'}}]->(hz_{hz})" +
                    $"-[:CAUSES]->(se_{ef});");
            }

            return sb.ToString();
        }

        private static CombatRule[] LoadAllRules()
        {
            string[] guids = AssetDatabase.FindAssets("t:CombatRule", new[] { RULES_DIR });
            var list = new List<CombatRule>(guids.Length);

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                CombatRule rule = AssetDatabase.LoadAssetAtPath<CombatRule>(path);
                if (rule != null) list.Add(rule);
            }

            if (list.Count == 0)
                Debug.LogWarning($"{LOG} No CombatRule assets found in {RULES_DIR}.");

            return list.ToArray();
        }

        private static string EscapeJson(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
        }

        private static string EscapeCypher(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            return s.Replace("'", "\\'");
        }
    }
}
#endif
